version: '3.9'

services:
  api-server:
    image: api-server
    container_name: api-server
    environment:
      - BACKEND_PORT=3000
      - DB_NAME=chomchob-testing
      - DB_HOST=maria-chomchob-testing
      - DB_USER=root
      - DB_PASS=1234
      - DB_PORT=3306
    networks:
      - app-network
    ports:
      - 3001:3000
    depends_on:
      - mariaDB

  # mongoDB:
  #   image: mongo
  #   container_name: mongo-chomchob-testing
  #   restart: always
  #   volumes:
  #     - ./data/mongoDB:/data/db
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=1234
  #   networks:
  #     - app-network
  #   ports:
  #     - 27017:27017

  mariaDB:
    image: mariadb:latest
    container_name: maria-chomchob-testing
    restart: always
    command: --max_allowed_packet=32505856
    environment:
      - MARIADB_DATABASE=chomchob-testing
      - MARIADB_ROOT_PASSWORD=1234
      - MARIADB_USER=root
      - MARIADB_PASSWORD=1234
    volumes:
      - ./data/mariaDB:/var/lib/mysql
    networks:
      - app-network
    ports:
      - 3307:3306

networks:
  app-network:
