version: '3.9'

services:
  api-server:
    image: api-server
    container_name: api-server
    restart: always
    environment:
      - BACKEND_PORT=3000
      - DB_NAME=chomchob-testing
      - DB_HOST=maria-chomchob-testing
      - DB_USER=root
      - DB_PASS=1234
      - DB_PORT=3306
      - DB_REDIS_URL=redis://redis-service:6379
      - SS_SECRET=ckdk3e9kcnmvwiedj23314kncknvszxnmcsldjkf3imkscnv0w32nrjklnsdf0cvn
    networks:
      - app-network
    ports:
      - 3001:3000
    depends_on:
      - redisDB
      - mariaDB

  redisDB:
    image: redis:latest
    container_name: redis-service
    restart: always
    volumes:
      - ./data/redisDB:/data
      - ./config/redis.conf:/redis.conf
    ports:
      - 6380:6379
    networks:
      - app-network
    command: redis-server /redis.conf
    depends_on:
      - mariaDB

  mariaDB:
    image: mariadb:latest
    container_name: maria-chomchob-testing
    restart: always
    command: --max_allowed_packet=32505856
    environment:
      - MARIADB_DATABASE=chomchob-testing
      - MARIADB_ROOT_PASSWORD=1234
      - MARIADB_USER=root
      - MARIADB_PASSWORD=1234
    volumes:
      - ./data/mariaDB:/var/lib/mysql
    networks:
      - app-network
    ports:
      - 3307:3306

networks:
  app-network:
